# Generated by Django 4.1.3 on 2022-11-11 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_profile_image_profile_profileimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followerId',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followingId',
            new_name='following',
        ),
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 22, 10, 40, 393244)),
        ),
    ]
