# Generated by Django 4.1.1 on 2022-11-14 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_followerscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 8, 50, 39, 716868)),
        ),
    ]
