# Generated by Django 4.1.1 on 2022-11-10 06:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_followerscount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userName',
        ),
        migrations.AlterField(
            model_name='likepost',
            name='userName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 13, 51, 59, 9576)),
        ),
    ]
