# Generated by Django 4.1.1 on 2022-11-01 03:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_profile_image_profile_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('create_at', models.DateTimeField(default=datetime.datetime(2022, 11, 1, 10, 11, 39, 791595))),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
