# Generated by Django 4.1.1 on 2022-11-10 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_comment_username_alter_likepost_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 10, 13, 53, 12, 74171)),
        ),
    ]
