# Generated by Django 4.1.3 on 2022-11-12 04:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_follow_contact_alter_post_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='follower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='following',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 11, 17, 36, 648584)),
        ),
    ]
