# Generated by Django 4.1.1 on 2022-11-02 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_auth_alter_post_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 15, 16, 59, 930136)),
        ),
    ]
