# Generated by Django 4.1.1 on 2022-11-14 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_createdat_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 14, 13, 8, 31, 616330)),
        ),
    ]
