# Generated by Django 4.0.7 on 2022-11-03 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_create_at_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 10, 19, 7, 532508)),
        ),
    ]
