<<<<<<< HEAD
# Generated by Django 4.0.7 on 2022-11-03 03:26
=======
# Generated by Django 4.1.1 on 2022-11-04 04:20
>>>>>>> 62a00160b19cfdc021cd549aad7c0fb477fbc743

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('core', '0010_alter_post_create_at'),
=======
        ('core', '0010_comment_alter_post_create_at'),
>>>>>>> 62a00160b19cfdc021cd549aad7c0fb477fbc743
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 10, 26, 43, 935865)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 20, 55, 446929)),
>>>>>>> 62a00160b19cfdc021cd549aad7c0fb477fbc743
        ),
    ]
