# Generated by Django 4.1.1 on 2022-11-04 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_alter_post_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 20, 55, 446929)),
        ),
    ]
