# Generated by Django 4.1.1 on 2022-11-04 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_comment_post_alter_likepost_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 15, 45, 39, 403223)),
        ),
    ]
